### ISSUE TITLE
connect to server

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-vscode#1]
The easiest protocol to use is the WebSockets JERKY protocol.

Start the server by generating a `build.sbt` file (or using coursier to do the same) asking for `ensime-server`, e.g. https://github.com/ensime/ensime-emacs/blob/master/ensime-startup.el or https://github.com/ensime/ensime-atom/blob/99f05e89876d5b1955cb3e4da89cb9375840aad7/lib/ensime-server-update.coffee

The API is documented in the `api` module of `ensime-server`, you might also need to write a parser to extract some basic information from the `.ensime` file.

Example payloads are in the tests of the `jerky` module.

Good luck @dragos !

**Comment by hedefalk** [comment]
Done.
